### ISSUE TITLE
Lodestar - Lodestar doesn't repair damaged vehicles near it

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1038]
The lodestar doesn't repair damaged vehicles near it even though it should. You can get as much ammo as you want from it, but no repairs.
Tested on Sanctuary and Solsar.

**Comment by Fate-JH** [comment]
This is actually an issue I know or, at least, part of one.  At least one of the flanking repair terminals of the Lodestar doesn't seem to be positioned correctly on the model.  Or maybe it doesn't spawn correctly.  It's honestly been a long time since I diagnosed the issue and I forget if I ever found a golden approach where the "hiding" terminal can be engaged without the other one also triggering.  There's also not much I can do about it.

If neither terminal is activating - check both sides - then I'll run through the logic for proximity terminals.

**Comment by ScrawnyRonnie** [comment]
Fixed in #1137 and can be closed.
