### ISSUE TITLE
Can no longer log out and switch to a different character - Gets hung connecting to server

### ISSUE THREAD

**Issue by ScrawnyRonnie** [psforever/PSF-LoginServer#1124]
As title says, we're no longer able to switch characters. It hasn't been around long; probably one of the last couple updates. 

Repro steps:
1) Be logged in
2) Esc Q to 'Quit' game and return to server selection screen
3) Select the server and click 'Play'

It will hang at connecting and display a message saying 'You have left the world'. Workaround is to close the client and launch again. Not a big deal, but worth a mention as it has been noticed by a few.

**Comment by Resaec** [comment]
I can recreate this. The server console loggs ``[ INFO] net.psforever.actors.net.LoginActor - Connect to world request for 'PSForever'`` and the client is stuck on "Connecting to World Server"

**Comment by Fate-JH** [comment]
The real question is how long this has been happening.  "Last couple of updates" since ...?

The server has two main aspects: the login (51000 normally) and the gameplay (51001 normally).  The server receives `ConnectToWorldRequestMessage` from the client which should be caught in `LoginActor` on the login side of things.  `LoginActor` should send `ConnectToWorldMessage` back to the client and kill its parent, thus ending the login behavior.  The client should send another `CTWRM` packet back to the server, but this time it should be caught by `SessionActor` on the gameplay side of things.  This starts the game in proper by requesting information about the client's token, retained by `AccountIntermediary`, based on that second `CTWRM`.

This is also the point before where the server is getting jammed up.  The second `CTWRM` is not getting picked up by another gameplay aspect.  I do not know why yet.

**Comment by Resaec** [comment]
This problem seems to appear with #1123

**Comment by ScrawnyRonnie** [comment]
The most recent evidence I could provide is from my stream on July 2nd. I switched from NC to TR and did not experience this. I did switch characters on a more recent stream, but the screen wasn't showing at that time. I don't think I would have closed out of the client and launched again though and it wasn't due to a crash.
