### ISSUE TITLE
Player not ejected from wall turret when base flips

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1144]
See video.

https://github.com/psforever/PSF-LoginServer/assets/77748540/02f1b941-e20c-44be-b126-b30c22992b31

**Comment by ScrawnyRonnie** [comment]
When a base is hacked the "normal" way it kicks anyone out and makes them inaccessible. Are there any fringe cases where a player could stay mounted in one while the base is hacked?  If it is possible to still be in one that would definitely need to be fixed.

To the way it was done here, do we need to address a GM command flipping a base since this wouldn't happen in a normal capture transaction?

**Comment by Dethdeath** [comment]
If the code already exists, perhaps GM flipping should also use it.
