### ISSUE TITLE
LLU invisible to some after vehicle death

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1153]
When a vehicle blows up with an LLU carrier inside it, only the former carrier can still see it. Other players that were near the death of the LLU carrier can not see the LLU anymore, that goes for the driver too.
Players that get onto the continent after the death of the LLU carrier can see it.

**Comment by ScrawnyRonnie** [comment]
For future reference, there is a half fix applied in #1146 here:
src/main/scala/net/psforever/objects/serverobject/damage/DamageableMountable.scala
Half fix due to the asynchronous nature of the things involved. Sometimes they fire in the order to make the LLU visible to others, sometimes they don't.
