### ISSUE TITLE
Water where it Dont Show

### ISSUE THREAD

**Issue by lazer1982** [psforever/PSF-LoginServer#1183]
On Forseral, 
![Fors](https://github.com/psforever/PSF-LoginServer/assets/99909749/c064722b-332b-4e91-9b62-b072cf6f7be7)
  North of Ogma  by the Tower, There a Spot where the Player Can Drown and the Vechs that are not Float-able Gets Stuck, Do know This Will not Bother VS players in Vech's Since they are inmune to the water But for TR and NC This is a Hidden Trap...

https://youtu.be/p87rv9jP1do

**Comment by Fate-JH** [comment]
On my way to test this destination, I started drowning about three or four times in the western plains area, especially around Ogma.  Looking at the environmental data for this zone, this is one of those places where I opted for a sea level rather than a bunch of surrounding pools and smaller inland pools and lakes.  Playing around in a nearby lake, the water level is correct, but the ground elevation is below sea level in these random regions.  There's perhaps even some areas that are just on the border where ducking would be enough to drown.

Given the awkward shape of the continent, blocking it out might be complicated.

**Comment by Fate-JH** [comment]
Okay, here's my proposal.  I'm trying to minimize land coverage of the water fields.
![forseral-map-divided-up-1](https://github.com/psforever/PSF-LoginServer/assets/16406615/2f67541e-2e81-4674-909e-cd59457aae38)
Eight ocean regions, nine smaller lakes.  I hope that I can combine some of those lakes - the three around Neit, and the lakes below Caer - and some of those lakes into the ocean regions - the small one in the north east with the ocean to the west.  If I could swallow that small lake near Anu by the ocean section to its south, that would be good too.

**Comment by Dethdeath** [comment]
Sounds good.

This pond near Lugh doesn't drown players:

![lugh](https://github.com/psforever/PSF-LoginServer/assets/77748540/83db3f56-f932-4a3e-8043-b67bc0b91a22)
