### ISSUE TITLE
Enemy AMS interference range way too large

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1211]
Friendly AMSes can be deployed right next to each other whilst enemy AMSes cannot be deployed closer than 125 meters from each other, this makes it hard to set them up in the same base or around towers. The interference range for enemy AMSes should be the same as the value for friendly ones.

**Comment by Fate-JH** [comment]
The faction affiliation blocking range is reversed right now and this will be fixed in a future PR.

Counterpoint: enemy AMS's blocking friendly AMS's exposes enemy AMS locations.  It would encourage hunting them down to make room for your own spawn points; but, the cloak bubble is supposed to be a defense against detection at a distance, not a method of exposure.
