### ISSUE TITLE
Implant terminals can't be hacked

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1213]
This is certainly a low priority bug, hopefully the fix for it requires little effort :P
The hacking progress bar works, but the terminal never gets hacked successfully.

**Comment by Fate-JH** [comment]
This is actually not as straightforward as it seems.  Implant terminals are composed of two components - the terminal interface and the terminal machine ("mech").  Both of these components be hacked to work properly; and, even if I bypassed the tough part and made it so that only one needed to be hacked, that'd only the easy part.  The problemsome part is that there are two active hacking points for the whole implant terminal assembly - one above and one below if I remember correctly - and it's not obvious which one affects which component.  Moreover, I can not casually switch from one to the other between what the client thinks I am interacting with and the one I want to interact with.

It's easy to determine what is happening when hacking an implant terminal machine and bounce a temporary hacked state change over onto the implant interface.
It's not so easy when hacking the implant terminal interface.  There's no easy room anywhere to remind the implant terminal machine it needs to set its temporary hacked state.
