### ISSUE TITLE
Drop pod client freeze

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1218]
Originally reported by Equinaux in #bug-report. Whoever is in a drop pod will experience a client freeze if their pod is shot at by a wall turret or spitfire turret.
See video:

https://github.com/user-attachments/assets/d47aa76e-21ca-4d89-b8d7-8f963614151d

**Comment by Fate-JH** [comment]
Low-effort prognosis: the drop pod is deleted from the client before the occupant gets to disembark, resulting in, naturally, the occupant being deleted too.  With the POV entity lost, the game doesn't know what region of the portal system it should display anymore and it culls out the world.  Also, the client softlocks, because it lost its POV entity.

**Comment by Fate-JH** [comment]
I've never been certain whether the player is "deleted" or if it is merely lost forever in the game's memory when its parent entity loses the reference to it before truning over control.  It'd be more or less the same thing.

**Comment by Fate-JH** [comment]
Boom.
``[ERROR] n.p.a.session.support.SessionData - AIDamage/Target: [player] has an invalid reference to thing with [droppod guid] in zone [name id]``
