### ISSUE TITLE
Invulnerable Vehicles

### ISSUE THREAD

**Issue by Fate-JH** [psforever/PSF-LoginServer#1227]
A report about fresh vehicles, hot off the spawn pad, not being affected by deployables properly.  Spitfires may or may not target but never do any damage.  Mines explode or may not explode but never do any dcamage.

**Comment by theonetrueduddy** [comment]
I'm not confident this is about the vehicles being invulnerable as so much it is the turrets dealing no damage. [See this clip](https://youtube.com/clip/Ugkxumb_0YbHo-7snnVMRSR-E6LgMKCUMwcV?si=ItviHe-P6i-q0-6V) from 2024/08/11 from the Sunday fight where knifing the turret causes it to shoot me but do no damage.

Also got other footage of the turrets dealing no damage to me in a MAX, as well as not damaging other vehicles, all in that video.

Can't comment for mines other than they have felt like that they don't always work for a while.

Will try to reproduce my findings on test, but that'll have to wait sadly.

**Comment by Dethdeath** [comment]
Afaik the new CE/mines issue only happens on #1226

I've made a lot of progress in unraveling the mystery.

It's not just invulnerable vehicles either, it's infantry too:
(also note how friendly fire from the boomers never stops working)

https://github.com/user-attachments/assets/6a84f3d5-e474-4741-bf43-0766c349a0f5

The mines in the video below were all laid by the same character:

https://github.com/user-attachments/assets/9c391513-cae2-4b94-b8aa-6437b0893f0a

Now for the explanation:
The bug is caused by the minelayer spawning on the same continent as the vehicle is pulled on. If the minelayer zones to another continent and comes back, their newly laid mines/boomers will now damage that vehicle, their old ones won't. That is how I laid the alternating working/not-working mines in the video above. The vehicle will stay immune to a minelayer that spawned on the same continent even if it's empty, as seen in the video featuring the Fury. As for the driver, their mine/boomer damage immunity entirely depends on where they spawned at. If they came from another continent before pulling the vehicle, they will be vulnerable to mines/boomers once they get out of the vehicle. If they spawned on the continent where the vehicle was pulled, they have a high chance of being invulnerable to mines/boomers.

Reproduction steps:
-Go to a continent with 2 opposing empire characters and make sure they each have a base they can spawn at.
-Suicide on each character and spawn at their respective bases.
-Travel or warp to one of these 2 bases with both characters.
-The character that the base belongs to pulls a vehicle.
-The character that is hostile to the base lays down some mines or boomers.
-The vehicle should be immune to all of these, the driver will usually be immune if they have spawned on the continent.
-Zone to another continent with the minelayer character and go back to make their new mines/boomers work again.

**Comment by Fate-JH** [comment]
The moment I read the parts of the instructions with the respawning and zoning and warping, I understood what the problem was.  You're messing with the `Sidedness` of the entities by doing that and most likely `/warp` is being used to expedite part of the travel required in the testing.  Most likely, the farther player will be warping to the enemy facility after respawn.

To run through it: when you first login, your character is set to `StrictlyBetweenSides` because random `Sidedness` can't be determined yet and it's not tracked in the database.  (We could, but why?)  When you physically travel, you encounter IFF doors that adjust the `Sidedness` of the targets that pass through them appropriately.  When you respawn, your character inherits the `Sidedness` of their spawn point, tube or AMS.  When spawning a vehicle, it inherits the `Sidedness` of the spawn pad.  When placing a mine, it inherits the `Sidedness` of the layer.  When you use `/warp`, your character maintains its previous `Sidedness` and can even be considered `InsideOf` when you are "outside of" a facility.  When you `/zone`, your character's `Sidedness` is reset to `StrictlyBetweenSides` which qualifies as either `InsideOf` or `OutsideOf`.

It's the ambiguity of your second instruction and your third instruction that causes issues.  If one player spawns `InsideOf` a facility at the spawn tubes and then they `/warp` to under the entrance gate, they are not on the same side as a player who spawned at an AMS deployed `OutsideOf` the facility under the same entrance gate.  The minelayer and the vehicle driver, being of different factions, will not be products of the same facility spawn, and one will probably `/warp` to expedite testing while the other will probably physically travel to the testing site.

tldr: whenever you use warping or zoning in your tests, have both characters touch an IFF door before setting up the test.

**Comment by Dethdeath** [comment]
I agree that sidedness is involved. One of my tests just confirmed it.
Why does this affect boomers when those should work both inside and outside?

During one of my tests just now I pulled a mosquito at the base I spawned at, flew to the enemy base, bailed out and tried to boomer an ANT. It did no damage, neither did mines I placed near the same vehicle.
After this I ran into the enemy base lobby and back out, explosions from new CE did damage now.
How did this character's sidedness break when they didn't warp anywhere? I repeated this test twice. Idk if it helps, but this was at Kusag, Ishundar, which is a tech plant.

The minelayer spawned at an amp station after this and the sidedness seemed correct here (everything did damage). So there might be an issue with tech plants?

**Comment by Dethdeath** [comment]
I suppose I can answer my own boomer question. If your character is "inside" you cannot damage characters/vehicles that are outside with explosions.

**Comment by Fate-JH** [comment]
Tech plants are interesting cases as they contain three vehicle spawn pads.  By default, a vehicle spawn pad is marked as `OutsideOf` since that is their default condition; but, the tech plant's lowest vehicle spawn pad is underground and behind a barrier-protected door and thus gets rebranded as `InsideOf`.  This is important because, as I mentioned, vehicles inherit the `Sidedness` of their originating pad.  You might wonder why this effort is exerted when it would be just as easy to mark vehicles as always `OutsideOf` since that's their primary operating area.  The answer to that is: the orbital strike will only damage things that are outside or are in the wiggle room between inside and outside, such as loitering near open doors.  The garage door resolves the `Sidedness` of the vehicle when it emerges, or that's the expectation at least.  Is it an edge case?  Yes.

Additionally, that means a mosquito spawned at a tech plant should count as `OutsideOf` the facility since the spawn pad is outside on the roof even if the terminal and the player are `InsideOf` the facility.  (And vehicle spawn pads are marked as `OutsideOf` by default, anyway.)

I tend to work out of Anguta Akna and Tootega on Ceryshen locally; but, will switch to Nerrivik for a while to attempt interactions within a tech plant.

**Comment by theonetrueduddy** [comment]
So got on to test to attempt reproduction, making sure to follow the advice regarding use of /warp and touching an IFF door;

1. Facility Phalanx turrets still don't deal damage in AI mode, _except_ in the cases where the owner of a vehicle exits _before or whilst_ being shot at (which kinda matches [this report from #bug-report](https://discord.com/channels/142775664192389121/295670273544290304/1272266439541129281) on discord)
2. Tower Phalanx turrets just don't seem to respond at all
3. Spitfires appear to work as expected, aside from when invoking `Sidedness` weirdness via warp and such

Regarding that first point, the consistency about when the Phalanx will and won't damage a vehicle feels weird;
- Single occupant vehicle, driver triggers = No Damage until exit vehicle, continues upon reentry
https://github.com/user-attachments/assets/2725df8d-d487-4bb4-b9fb-62ac54bb9fcf
- Multiple occupant vehicle (MOV) owner is absent, gunner triggers = No Damage until gunner exits
https://github.com/user-attachments/assets/04c3709c-24ce-4882-8582-706faf48773b
- MOV and owner triggers as gunner = No Damage until driver exits
https://github.com/user-attachments/assets/e3b06734-4dbd-4f68-a73b-5de6a3a51a08
- MOV and gunner triggers and then exits first = No Damage until driver exits
https://github.com/user-attachments/assets/8aa42b0b-8f05-4fb6-838c-ba9cae4b247c
- MOV and gunner triggers and stays, driver exits first = No Damage but is shot at by turret for limited time
https://github.com/user-attachments/assets/e4ab43bb-12f9-4b20-9260-699fc494510d
- MOV owner absent and gunner triggers and exits = Damage, but if owner now enters = No Damage until exit again
https://github.com/user-attachments/assets/e21e1a37-af56-469d-aeed-4686fb9417aa
- MOV and owner triggers as gunner = No Damage until exit, continues when enters again
https://github.com/user-attachments/assets/b219e571-0824-4f81-bc59-7ce4adf4c033
- MOV and gunner triggers then exits and returns = No Damage, even after driver exits
https://github.com/user-attachments/assets/646405c0-19e0-4c84-a8a8-d25f03395f93

And those were just the cases I thought to cover!

My intention had been to test `Sidedness` for the Phalanx turret issues, but after what I found now I have no idea... Perhaps needs to be its own issue.
