### ISSUE TITLE
Cerberus Damage

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1235]
Cerberus turret damage is too high in some cases, it becomes even more clear when compared to spitfire turrets.

Wiki:
>The Cerberus Turret doesn't do a lot of damage to vehicles and Infantry, and will not fire upon Infantry unless fired upon.

Game help message:
>The end result is an automatic defense turret that, while fairly ineffective against infantry, is decimating to flight vehicles.

Lightning vs Spitfire (around 37 seconds TTK):

https://github.com/user-attachments/assets/a71a9343-4510-4b76-92f1-dc9abf1527f0

Lightning vs Cerberus (around 20 seconds TTK):

https://github.com/user-attachments/assets/ec60433b-2f38-4397-8465-36bf7fe1beec

Rexo vs Spitfire (around 4 seconds TTK):

https://github.com/user-attachments/assets/ccc6361f-efe9-4575-a9be-06e739da921e

Rexo vs Cerberus (around 9 seconds TTK):

https://github.com/user-attachments/assets/5f52c114-28e4-40e7-94fa-45a695df3c96

So it's fairly obvious the TTK of the cerberus turret vs ground vehicles especially is too small. It also seems too small vs infantry as they used to take longer to kill infantry. I don't know if we have exact numbers for this somewhere, but that would be preferred over guesswork 😛

**Comment by Fate-JH** [comment]
After checking the ADB entry for the `spitfire_aa`, the `spitfire_aa_weapon`, the `spitfire_aa_ammo` and the `spitfire_aa_projectile`, all the numbers in our custom definitions line up correctly.  The Cerebus has an automatic firing rate of 300 and the normal Spitfire has an automatic fire rate of 150.  The Cerebus does 5 damage per shot to Infantry, the normal Spitfire does 15 damage per shot to Infantry.  There's nothing in the values to indicate how the retaliatory period for spitfires compares to the standard shooting mechanic, if there is any difference, but given that the only thing I can do is point and shoot, there's nothing I can do to manually adjust the fire rate.

I think I can modify the damage from the `Cerebus` so that any target that isn't a flying vehicle gets damage reduced by one or two points.
