### ISSUE TITLE
Medical - Medical Applicator - Healing - The Medical Applicator is healing players too quickly

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#468]
The Medical Applicator is healing players too quickly.

The tick time for heals should be 0.5 seconds. I believe it is set to 0.25 seconds currently.

``add_property applicator firemode0_refiretime 250`` <-- probably the current value
``add_property applicator heal_time 500`` <-- correct value

https://www.youtube.com/watch?v=pu9NZOCPhEQ#t=03m58s (timestamp at 3min, 58 sec)

**Comment by jgillich** [comment]
Quoting @Mazo:

> But med applicator seems correct to me. It's actually a client side thing. When you use it it starts sending packets to the server with ticks of how often to heal you

 Client sends 4 `UseItemMessage`s per second (roughly every 0.25 seconds) and all the server does is add 10 HP each time.

But I wonder if the `UseItemMessage` is meant to be interpreted that way. What if instead of "heal the player", it just signals to the server that the player is (still) using the applicator? There's no real reason why the client should get to decide the tick rate.

**Comment by Mazo** [comment]
I started writing some code to fix this, then went back and double checked.

The tick is already ~500ms. Here's an example output of the milliseconds between ticks being picked up by `WSA`:

```
499.73
499.94
499.96
499.98
416.76
500.19
533.36
549.99
516.66
499.99
483.17
516.73
500.01
499.99
```
