### ISSUE TITLE
Chat - Squads - Chat can stop working while in a Squad

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#472]
Chat can stop working while in a Squad.

**Comment by NickPSF** [comment]
Must fix for event

**Comment by Fate-JH** [comment]
After looking things over, my only conclusion is that squad comms issues are related to persistence issues.

There's a defined entry point - `JoinChannel` - which is related to `Join` (squad), and a defined exit point - `LeaveChannel` - which is related to `Leave` (squad).  The rest of the magic happens within `ChatActor` itself when sent a `ChatMsg` message exactly in the state the server received it.  The collapsing persistence code for dealing with squads is limited mostly to participation and not visual elements, since those won't matter in a few short seconds.  Upon re-establishment of persistence, I can not guarantee, with the current code, that squad comms are restored properly.

**Comment by NickPSF** [comment]
Fixed awaiting check in
