### ISSUE TITLE
Weapon audio with secondary fire mode

### ISSUE THREAD

**Issue by ScrawnyRonnie** [psforever/PSF-LoginServer#961]
When using secondary mode, such has triple shot with the Jackhammer, other players only hear the sound of one shot. The player using the secondary mode hears the correct weapon sound. Weapons this has been observed with:
- Jackhammer: If you are in secondary mode and hold the mouse down, it does a triple shot, then there is a few second delay until the next triple shot. Because your mouse is 'clicked' the whole time, the other players hear constant shots as if it were in primary mode.
- Medium Assault pistols

This also happens with knives. You can't hear them and the animation the other player does is the primary swinging the knife rather than the secondary straight poke animation.

None of this effects damage; only audio and animations.

**Comment by Fate-JH** [comment]
It's going to be difficult to work on this for me due to quirky sound issues.  When I mute one PlanetSide instance, I will have effectively muted all PlanetSide instances.  I can not isolate one client from another in terms of audio output and will hear what any number of clients hear at the same time.

**Comment by Dethdeath** [comment]
For some visual feedback instead of audio, weapons like the Lasher, Beamer and Punisher all suffer from this problem too. AP fire mode will just show primary blue orbs on the Lasher and I believe that on the Beamer it was reversed and always showed purple.

I did some vehicle tests and the Skyguard and Reaver both also have the wrong visual/audio ouput.
