### ISSUE TITLE
Returning Vehicle ammo crashes the client

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#997]
See included video and packet capture.
https://user-images.githubusercontent.com/77748540/170845266-84b60d5d-6112-467e-a6cd-1cc3562b59a0.mp4
[PSCap-AmmoReturncrash.zip](https://github.com/psforever/PSF-LoginServer/files/8792266/PSCap-AmmoReturncrash.zip)

**Comment by Fate-JH** [comment]
I think the client crashed for other reasons, not for returning the ammo box.
Gonna ask you if you can repeat and reproduce in the future of 2023.

**Comment by ScrawnyRonnie** [comment]
Tried this again last night. It crashed the client from loading the trunk. Replacing an ammo box multiple times when the trunk is full (no room for another box) causes it to crash. 
Before replacing ammo box and normal looking;
![image](https://user-images.githubusercontent.com/73139382/215115904-f57b794d-e44a-476a-b33c-83f557868b07.png)
Top left box replaced. It looks like it stacks them up or something? The number looks weird:
![image](https://user-images.githubusercontent.com/73139382/215116135-5d3daf3c-ea96-4195-b4aa-1e000a769cb0.png)
Attempting to grab another ammo box from the terminal crashes the client.

It also happens if you clear the trunk and start adding ammo in and you're weird and decide to keep putting the next ammo box in the place of the first box. It will eventually crash too. It simply has to do with putting an ammo box in the place of another one that is already there causing some weird stacking issue.

This would be mitigated by destroying the ammo box first instead of putting one in its place or by clearing the trunk, but worth a look in the future to cover all bases.
